[project]
name = "fhir-to-lakehouse"
version = "1"
description = "Reads FHIR bundles from Kafka, encodes them using the Pathling encoders, and stores them as Delta Lake tables."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pathling==9.0.0",
    "delta-spark==4.0.0",
    "typed-settings[attrs]==25.2.0",
    "loguru==0.7.3",
    "opentelemetry-api==1.38.0",
    "opentelemetry-sdk==1.38.0",
    "opentelemetry-exporter-prometheus==0.59b0",
    "tenacity==9.1.2",
    "tomli==2.3.0",
    "click==8.3.0",
    "deltalake[pyarrow]==1.2.1",
    "boto3==1.40.65",
]

[dependency-groups]
dev = [
    "kafka-python==2.2.15",
    "pandas==2.3.3",
    "pytest==8.4.2",
    "pytest-cov==7.0.0",
    "testcontainers[minio]==4.13.2",
    "ruff==0.14.3",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
